name: Image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v2
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/547950975109/locations/global/workloadIdentityPools/gh-pool/providers/gh-pool'
        service_account: 'gh-runner@mkm-cloud.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Set up GCR
      run: gcloud auth configure-docker us-docker.pkg.dev
      
    - name: Setup ko
      uses: imjasonh/setup-ko@v0.4
      env:
        KO_DOCKER_REPO: us-docker.pkg.dev/mkm/generated-secrets
    - run: ko publish --platform=linux/amd64,linux/arm64 ./
