name: Image build gh

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup ko
        uses: imjasonh/setup-ko@v0.4

      - name: Build image
        run: |
          mkdir -p dist
          ko resolve -f controller.yaml --bare --platform=linux/amd64,linux/arm64 >dist/controller.yaml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Development Build"
          files: |
            dist/*
