name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Set up Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # tag=v3
        with:
          go-version: 1.17

      - name: Setup ko
        uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # tag=v0.4

      - name: Setup kubecfg
        run: |
          curl -sLf https://github.com/kubecfg/kubecfg/releases/download/v0.25.0/kubecfg_Linux_X64 >/usr/local/bin/kubecfg
          chmod +x /usr/local/bin/kubecfg

      - name: Prepare dist/
        run: mkdir -p dist

      - name: Render jsonnet
        run: |
          kubecfg show controller.jsonnet --export-dir yml

      - name: Build image
        run: |
          ko resolve -f yml --bare --platform=linux/amd64,linux/arm64 >dist/controller.yaml

      - name: Prepare jsonnet release
        run: |
          cp controller.jsonnet dist/
          cp release.jsonnet dist/release.jsonnet
          sed  '/ - image:/!d;s/.*image: //' dist/controller.yaml >dist/image.txt

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*
